name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true
          cache: true

      - name: Get dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64, arm64]
        exclude:
          - os: windows
            arch: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true
          cache: true

      - name: Build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          # Add .exe extension for Windows builds
          if [ "${{ matrix.os }}" = "windows" ]; then
            go build -v -o sgpt.exe ./cmd/sgpt
          else
            go build -v -o sgpt ./cmd/sgpt
          fi

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sgpt-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            sgpt
            sgpt.exe
          if-no-files-found: ignore 