name: Docker

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'cmd/**'
      - 'pkg/**'
      - '.github/workflows/docker.yml'
  schedule:
    - cron: '0 2 * * 0'  # Weekly on Sundays at 2:00 AM UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      
      - name: Build sgpt binary
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o sgpt -ldflags="-s -w" ./cmd/sgpt
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/sgpt
          tags: |
            type=raw,value=latest
            type=sha,format=short
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max 