name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Debug Files
        run: |
          echo "Current directory:"
          pwd
          echo "Listing files in root directory:"
          ls -la
          echo "Checking .goreleaser.yaml file:"
          cat .goreleaser.yaml || echo "No .goreleaser.yaml file"
          echo "Checking .goreleaser.yml file:"
          cat .goreleaser.yml || echo "No .goreleaser.yml file"
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: true
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 